name: abokamall
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  image_picker: ^1.0.7
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  url_launcher: ^6.2.5
  get_it: any
  flutter_secure_storage: any
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  hive_flutter: any
  hive: any
  google_sign_in: ^6.0.0
  cached_network_image: ^3.3.1
  dartz: any
  intl_date_helper: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: any
  build_runner: any
  analyzer: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"

flutter:
  uses-material-design: true
